// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarea8_P3.Data;

namespace Tarea8_P3.Migrations
{
    [DbContext(typeof(vacunadosDbContext))]
    [Migration("20210317195320_Base-de-Datos-Arreglada")]
    partial class BasedeDatosArreglada
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Tarea8_P3.Data.vacunados", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Latitud")
                        .HasColumnType("TEXT");

                    b.Property<string>("Longitud")
                        .HasColumnType("TEXT");

                    b.Property<string>("apellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("fecahDosis1")
                        .HasColumnType("TEXT");

                    b.Property<string>("fecahDosis2")
                        .HasColumnType("TEXT");

                    b.Property<string>("fechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("provincia")
                        .HasColumnType("TEXT");

                    b.Property<long>("telefono")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tipoVacuna")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
